#+title: Contributions d'Etalab pendant la pandémie Covid-19
#+lang: fr
# #+description: Contributions d'Etalab pendant la pandémie Covid-19

* Header

# The Header section has to be named "Header".

Chronologie des contributions d'[[https://www.etalab.gouv.fr/][Etalab]] à l'information pendant la
pandémie Covid-19.

* Publication d'un premier jeu de données de Santé Publique France
  :PROPERTIES:
  :data-category: Données
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-03-10 mar.>
  :END:

Etalab travaille avec Santé Publique France pour publier le jeu de
données du nombre de cas confirmés au Covid-19.

Données : https://www.data.gouv.fr/fr/admin/dataset/5e689ada634f4177317e4820/

* Mise en ligne des chiffres clés concernant l'épidémie de COVID19 en France
  :PROPERTIES:
  :data-category: Données
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-03-12 jeu.>
  :END:

Etalab contacte les auteurs du dépôt github.com/opencovid19-fr/data et
publie un jeu de données issue du travail de volontaires contribuant à
ce dépôt.

Données : https://www.data.gouv.fr/fr/datasets/chiffres-cles-concernant-lepidemie-de-covid19-en-france/

* Migration de data.gouv.fr vers udata 2.0
  :PROPERTIES:
  :data-category: Infrastructure
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-03-16 lun.>
  :END:

Etalab travaillait depuis longtemps sur la version 2.0 de [[https://github.com/opendatateam/udata][udata]].
L'équipe effectue la migration vers cette nouvelle version.

* Ouverture des données de geodes.santepubliquefrance.fr
  :PROPERTIES:
  :data-category: Infrastructure
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-03-18 mer.>
  :END:

Etalab travaille avec Santé Publique France à l'ouverture des données
mises à disposition sur le site https://geodes.santepubliquefrance.fr.

* Création d'une organisation pour Santé Publique France
  :PROPERTIES:
  :data-category: Infrastructure
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-03-19 jeu.>
  :END:

Publication par Etalab des données SPF sur une nouvelle organisation
SPF de data.gouv.fr (les fichiers publiés sont récupérés manuellement
depuis geodes).

Provision d’un serveur data.gouv.fr pour réceptionner les données de
SPF, mise en place de la sychronisation entre les fichiers de SPF et
un répertoire de ce serveur (les données SPF ne sont pas encore
disponibles).

* Amorce du travail sur l'algorithme d'orientation Covid-19
  :PROPERTIES:
  :data-category: Algorithmes
  :icon-color: green
  :fa-icon: fa-plus
  :image-src: https://raw.githubusercontent.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/master/demonstrateur.png
  :image-caption: Capture d'écran du démonstration de l'algorithme d'orientation Covid-19
  :date: <2020-03-20 ven.>
  :END:

Héla Ghariani (de la Délégation numérique en Santé au ministère de la
Santé) sollicite les développeurs de la DINUM pour de l'aide sur la
publication de l'algorithme d'orientation Covid-19, algorithme déjà
utilisé sur sur le site https://maladiecoronavirus.fr.

* Début des travaux sur une application d'orientation Covid-19
  :PROPERTIES:
  :data-category: Applications
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-03-31 mar.>
  :END:

Échanges entre Etalab avec le Service d'information du gouvernement
pour élaborer un questionnaire d'orientation similaire à celui qui est
disponible sur https://maladiecoronavirus.fr, reprenant l'algorithme
d'orientation tel qu'il est documenté sur [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation][ce dépôt]].

* Mise en ligne de l'application d'orientation Covid-19
  :PROPERTIES:
  :data-category: Applications
  :icon-color: green
  :fa-icon: fa-plus
  :image-src: https://raw.githubusercontent.com/etalab/covid19-timeline/master/docs/img/questionnaire-orientation.png
  :image-caption: Page d'accueil du questionnaire d'orientation Covid-19
  :date: <2020-04-08 mer.>
  :END:

Le service d'information du gouvernement met en production une
première version du [[https://www.gouvernement.fr/info-coronavirus/orientation-medicale][questionnaire d'orientation]] développé par Etalab.

* Partage des données du questionnaire d'orientation avec l'institut Pasteur
  :PROPERTIES:
  :data-category: Données
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-04-13 lun.>
  :END:

Etalab partage les premières données reçues depuis le questionnaire
d'orientation Covid-19 avec l'institut Pasteur.

* Publication du tableau de bord des aides aux entreeprises et des données associées
  :PROPERTIES:
  :data-category: Applications
  :icon-color: green
  :fa-icon: fa-plus
  :image-src: https://raw.githubusercontent.com/etalab/covid19-timeline/master/docs/img/tbd-entreprises.png
  :image-caption: Page d'accueil du tableau de bord entreprises
  :date: <2020-04-20 lun.>
  :END:

Création et publication d'un [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-versees-fonds-solidarite][outil de type tableau de bord]]
permettant de visualiser la répartition des aides financières 
provenant du Fonds de Solidarité mis en place par le gouvernement.

Intégration de ce tableau de bord "aides financières" au [[https://dashboard.covid19.data.gouv.fr/aides-entreprises?location=FRA][tableau de bord général]]
ainsi qu'au [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-versees-fonds-solidarite][portail du ministère de l'Economie]]

Les données sont publiées sur la plateforme 
[[https://www.data.gouv.fr/fr/datasets/donnees-relatives-au-fonds-de-solidarite-mis-en-place-dans-le-cadre-de-lepidemie-de-covid-19/][data.gouv.fr]]

Le code source du tableau de bord est en open source et publié sur [[https://github.com/etalab/dashboard-aides-entreprises][ce dépôt]]
et [[https://etalab.github.io/dashboard-aides-entreprises/][documenté ici]]. 

* Point de contact avec les auteurs d'AlloCovid
  :PROPERTIES:
  :data-category: Algorithmes
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-04-28 mar.>
  :END:

Les auteurs d'AlloCovid se sont appuyés sur la [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation][documentation de
l'algorithme d'orientation Covid-19]].

* Mise à jour n°1 du tableau de bord des aides aux entreprises
  :PROPERTIES:
  :data-category: Applications
  :icon-color: green
  :fa-icon: fa-plus
  :image-src: https://raw.githubusercontent.com/etalab/covid19-timeline/master/docs/img/tbd-entreprises.png
  :image-caption: Page d'accueil du tableau de bord entreprises
  :date: <2020-05-13 mer.>
  :END:

Mise à jour conséquente du [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-versees-fonds-solidarite][tableau de bord]] des aides aux entreprises
permettant de visualiser la répartition des aides financières.
S'ajoute alors à la visualisation des données du [[https://www.data.gouv.fr/fr/datasets/donnees-relatives-au-fonds-de-solidarite-mis-en-place-dans-le-cadre-de-lepidemie-de-covid-19/][Fonds de Solidarité]],
celles des [[https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-prets-garantis-par-letat-dans-le-cadre-de-lepidemie-de-covid-19/][Prêts garantis par l'Etat]], et des [[https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-reports-decheances-fiscales-accordes-dans-le-cadre-de-lepidemie-de-covid-19/][Reports d'échéance
fiscale]].  Tous ces jeux de données sont publiés sur le portail
[[https://data.gouv.fr][data.gouv.fr]]

Intégration de ce tableau de bord "aides financières" au [[https://dashboard.covid19.data.gouv.fr/aides-entreprises?location=FRA][tableau de
bord général]] ainsi qu'au portail du ministère de l'Economie sur les
pages suivantes : [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-versees-fonds-solidarite#]["prêts garantis par l'Etat"]], [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-versees-pge#]["prêts garantis par
l'Etat"]], [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-report-echeances#]["reports d'échéance"]].

Le code source du tableau de bord est en open source et publié sur [[https://github.com/etalab/dashboard-aides-entreprises][ce
dépôt]] et [[https://etalab.github.io/dashboard-aides-entreprises/][documenté ici]].

* Publication des données des foires aux questions ministérielles
  :PROPERTIES:
  :data-category: Données
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-06-09 mar.>
  :END:

Etalab accompagne le service d'information du gouvernement dans la
publication des contenus des foires aux questions publiées par les
sites de l'État lors de la lutte contre la pandémie Covid-19.

Données : https://www.data.gouv.fr/fr/datasets/foires-aux-questions-publiees-par-les-administrations-dans-le-cadre-de-la-gestion-de-la-pandemie-covid-19/

* « Comment les administrations ont collaboré à l’ouverture des données du Coronavirus : le cas français »
  :PROPERTIES:
  :data-category: Publications
  :icon-color: green
  :fa-icon: fa-plus
  :date: <2020-06-09 mar.>
  :END:

Etalab publie un article de synthèse sur la façon dont les
administrations ont collaboré à l'ouverture des données liées au
Covid-19.

Source : https://www.etalab.gouv.fr/comment-les-administrations-ont-collabore-a-louverture-des-donnees-du-coronavirus-le-cas-francais

* Mise à jour n°2 du tableau de bord des aides aux entreprises
  :PROPERTIES:
  :data-category: Applications
  :icon-color: green
  :fa-icon: fa-plus
  :image-src: https://raw.githubusercontent.com/etalab/covid19-timeline/master/docs/img/tbd-entreprises.png
  :image-caption: Page d'accueil du tableau de bord entreprises
  :date: <2020-06-12 mer.>
  :END:

Mise à jour du [[https://aides-entreprises.data.gouv.fr/][tableau de bord]] des aides aux entreprises permettant de
visualiser la répartition des aides financières.  S'ajoute alors à la
visualisation des données du [[https://www.data.gouv.fr/fr/datasets/donnees-relatives-au-fonds-de-solidarite-mis-en-place-dans-le-cadre-de-lepidemie-de-covid-19/][Fonds de Solidarité]], des [[https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-prets-garantis-par-letat-dans-le-cadre-de-lepidemie-de-covid-19/][Prêts garantis
par l'Etat]], et des [[https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-reports-decheances-fiscales-accordes-dans-le-cadre-de-lepidemie-de-covid-19/][Reports d'échéance fiscale]].  Tous ces jeux de
données sont publiés sur le portail [[https://www.data.gouv.fr/fr/datasets/donnees-relatives-au-dispositif-dactivite-partielle-mis-en-oeuvre-dans-le-cadre-de-lepidemie-de-covid-19/][data.gouv.fr]].

Intégration de ce tableau de bord "aides financières" au [[https://dashboard.covid19.data.gouv.fr/aides-entreprises?location=FRA][tableau de
bord général]] ainsi qu'au portail du ministère de l'Economie sur les
pages suivantes : [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-versees-fonds-solidarite#]["prêts garantis par l'Etat"]], [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-versees-pge#]["prêts garantis par
l'Etat"]], [[https://www.economie.gouv.fr/covid19-soutien-entreprises/aides-report-echeances#]["reports d'échéance"]] [[https://www.economie.gouv.fr/covid19-soutien-entreprises/activite-partielle#]["activité partielle"]].

Le code source du tableau de bord est en open source et publié sur [[https://github.com/etalab/dashboard-aides-entreprises][ce
dépôt]] et [[https://etalab.github.io/dashboard-aides-entreprises/][documenté ici]].

* Footer

Retrouvez le code source de ce site sur [[https://github.com/etalab/covid19-timeline][ce dépôt]], publié sous licence libre.

# The Footer section has to be named "Footer".
